service: elasticsearch

provider:
  name: aws
  runtime: python3.6
  role: arn:aws:iam::063414442810:role/serverless-lambda-full
  stage: dev


package:
  exclude:
    - test.py

plugins:
  - serverless-python-requirements
  - serverless-secrets-plugin

custom: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

functions:
  process:
    handler: es_handler.process_stream
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - articles
              - StreamArn
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - articles
              - Arn
    environment:
      ES_ENDPOINT: ${self:custom.ES_ENDPOINT}
      REGION: ${self:custom.REGION}
