service: dynamodb_elasticsearch

provider:
  name: aws
  runtime: python3.6
  role: arn:aws:iam::063414442810:role/serverless-lambda-full
  region: us-east-2
  stage: dev


package:
  exclude:
    - test.py

plugins:
  - serverless-python-requirements
  - serverless-secrets-plugin

custom: ${file(secrets.${opt:stage, self:privoder.stage}.yml)}

functions:
  process:
    handler: handler.process
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - articles
              - StreamArn
    environment:
      ES_ENDPOINT = ${self:custom.ES_ENDPOINT}
      REGION = ${self:custom.REGION, self:provider.region}
